{
 "title": "main",
 "time": { "from": "2019-07-08T09:58:32.519Z", "to": "2019-07-08T15:58:32.519Z" },
 "panels": [
  {
   "title": "Total Burned Calories (week)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gauge_burned_calories{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Total Training Sessions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_activity_total{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\",type=\"activity\"}",
     "legendFormat": "total training sessions"
    }
   ]
  },
  {
   "title": "Total Running Sessions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "counter_running_total{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\",type=\"activity.running\"}"
    }
   ]
  },
  {
   "title": "Training Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_training_load{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Burned Calories (last session)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "gauge_burned_calories{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Running Cadence",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_running_cadence{endpoint=\"http\",instance=\"10.1.2.33:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-2-bmqn5\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "VO2 Max",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 3 },
   "targets": [
    {
     "expr": "gauge_vo2max{endpoint=\"http\",instance=\"10.1.2.33:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-2-bmqn5\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Heart Rate Max",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_heart_max{endpoint=\"http\",instance=\"10.1.2.33:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-2-bmqn5\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Last Running Distance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gauge_running_distance{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "Total Running Distance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "gauge_running_distance{endpoint=\"http\",instance=\"10.1.2.29:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-1-grd5r\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "POLAR FLOW API - PROCESS CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{endpoint=\"http\",instance=\"10.1.2.33:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-2-bmqn5\",service=\"polar-flow-api\"}"
    }
   ]
  },
  {
   "title": "POLAR FLOW API - JVM USED METASPACE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",endpoint=\"http\",id=\"Metaspace\",instance=\"10.1.2.33:8080\",job=\"polar-flow-api\",namespace=\"microservices\",pod=\"polar-flow-api-2-bmqn5\",service=\"polar-flow-api\"}"
    }
   ]
  }
 ]
}